sonar.projectKey=core_go-io
sonar.projectName=core/go-io
sonar.sources=.
sonar.exclusions=**/vendor/**,**/third_party/**,**/.tmp/**,**/gomodcache/**,**/node_modules/**,**/*_test.go
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**,**/third_party/**,**/.tmp/**,**/gomodcache/**,**/node_modules/**
sonar.go.coverage.reportPaths=coverage.out
